const ActionTypes = {
  ADD_PRODUCT: "ADD_PRODUCT",
  DELETE_SELECTED_PRODUCT: "DELETE_SELECTED_PRODUCT",
  EDIT_SELECTED_PRODUCT: "EDIT_SELECTED_PRODUCT",
  DISPLAY_PRODUCTS: "DISPLAY_PRODUCTS",
  SEARCH_PRODUCTS: "SEARCH_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
};

export default ActionTypes;
