const ActionTypes = {
  ADD_PRODUCT: "ADD_PRODUCT",
  DELETE_SELECTED_PRODUCT: "DELETE_SELECTED_PRODUCT",
  EDIT_SELECTED_PRODUCT: "EDIT_SELECTED_PRODUCT",
  DISPLAY_PRODUCTS: "DISPLAY_PRODUCTS"
};

export default ActionTypes;
